### ISSUE TITLE
"index out of range"

### ISSUE THREAD

**Issue by reppolice** [emdoyle/chess_ai#1]
Hi,

I am quite sure the code right now is offered with no guarantees of any sort, anyway my first run after "softlinking" the two directories you hardcoded gave me.

python3 deepmind_mcts.py 
Traceback (most recent call last):
  File "deepmind_mcts.py", line 112, in <module>
    class MCTS:
  File "deepmind_mcts.py", line 120, in MCTS
    prev_mcts=None, temperature=True, version=util.latest_version(), startcolor=True):
  File "/notebooks/chess_ai/pychess_utils.py", line 80, in latest_version
    return sorted(versions, reverse=True)[0]

IndexError: list index out of range

I am also curious about MCTS.dot, I attempted a conversion to PNG but that gave me a stern warning and did not immediately impress! Is it supposed to be a graph of the DL network?  I am on the latest Ubuntu, looks like you are on a Mac

**Comment by emdoyle** [comment]
Hey!

To be honest I didn’t really expect anyone to find this repo at this point actually.  It is in a very, very rough state and doesn’t really have any instructions for someone else to use it (as you found out).

I believe the directory that holds my trained model versions (“Export/“ I believe if you look into pychess_utils.py) is gitignored right now since I didn’t want any data files cluttering the repo, but I totally didn’t realize that this would break it for someone else attempting to run it.  I’m actually in Barcelona on vacation right now without my laptop so I can’t fix it, but I’ll add the directory to the repo when I get back and that error should go away!

MCTS.dot is wayyyy out of date at this point and I think I scrapped the script that generates it but basically it exported the Monte Carlo tree in .dot format for GraphViz after a certain number of simulations.  I used it to check that each node was incrementing its simulations and wins correctly when I first built MCTS (with playouts and no support from a neural net).

Anyways the state of the repo right now is:

 version2.py holds a TF implementation of the neural network described in the AlphaGo Zero paper

deepmind_mcts.py holds an implementation of Monte Carlo Tree search as described in the same paper (leveraging NN predictions to guide the search)

self_play.py uses that MCTS implementation to generate chess game data by playing itself

player_eval.py plays the latest version of the neural network against the best version and conditionally updates the version number of the best version (if the latest version wins 55% out of 400).

I’m still working out bugs and trying to figure out ways to massively boost performance so I dont have to pay for Cloud computing time but it may eventually come to that anyway due to the size of the network and depth of the Monte Carlo tree.

Anyway please let me know if you have any suggestions to move this forward!  I left self_play running on my laptop so I should come back to a decent amount of data for the training pipeline, but long term I need to find better ways to scale.

Thanks,
Evan

**Comment by emdoyle** [comment]
Oh also I don’t think you’ll be able to run the MCTS without using tensorflow-serving to serve a version of the NN.  If I remember correctly you might be able to run train.py and export a version of the model automatically, but I think you’ll need at least one csv data file in the right directory to run the training op...  Basically I’ll need to un-ignore some stuff for this to work as-is.  Should be able to do that on Monday when I’m back at my laptop!

Evan

**Comment by reppolice** [comment]
Thanks, that's much more than anyone has the right to expect! Indeed the Export is not there, I thought the error was related to missing entries in that dir but instead of more troubleshooting on my part it seemed reasonable to ask you about the status of things.

**Comment by reppolice** [comment]
I just realized the dependency on TF-serving makes it Python2 only. I don't know if it is a kink of my Ubuntu, but apparently TF-serving has to be installed as root. Still,


`python deepmind_mcts.py`
...
File "/home/agi/itu/chess_ai/rpc_client.py", line 6, in <module>
    from proto_files import predict_pb2, prediction_service_pb2, model_pb2, model_pb2_grpc


From what I could gather, this is a kink in TF-serving, that requires the bazel build, is there a way forward?

**Comment by emdoyle** [comment]
I remember this being a huge pain!  To get around the Python2 requirement of TF-serving I just used a separate virtualenv specifically to serve the model, definitely not a pretty solution but it worked for my purposes :)

The bazel build is the only way I was able to get it to work (make sure to use the optimization parameters listed in the installation, I think its like 10-50x faster on my machine) and my installation was hacked together since it technically doesn't support Mac OS.  I ended up manually copying those proto files I found in a forum post for people using it on Mac and got it to work.  That shouldn't be necessary on Ubuntu.

At this point though I have a version of my model on Google Cloud Platform so I no longer need to use TF-serving myself, but the costs (and the speed) of actually training it have discouraged me.  I now understand the scale of computing resources a company like Deepmind (or any at the edge of ML) requires.  If you're interested though, here is the paper I was trying to preempt/emulate: https://arxiv.org/pdf/1712.01815.pdf
